[package]
name = "url"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
failure = "0.1.8"
log = "0.4.14"
pretty_env_logger = "0.4.0"
structopt = "0.3.25"
urlencoding = "2.1.0"
